services:
  backend:
    image: lazarpanov/backend:latest
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/book-store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: book-store
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  db_data:
