---
name:  docker-build-and-push

on:
  workflow_dispatch:

jobs:
  # run-lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Run Super-Linter
  #       uses: github/super-linter@v5
  #       env:
  #         VALIDATE_ALL_CODEBASE: true
  #         DEFAULT_BRANCH: "master"
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  docker-build-and-push:
    runs-on: ubuntu-latest
    # needs: run-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run:
          docker build -t lazarpanov/backend:latest ./backend
          docker push lazarpanov/backend:latest

      - name: Build and push database image
        run:
          docker build -t lazarpanov/database:latest ./database
          docker push lazarpanov/database:latest

          





          
